version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:${DATABASE_PORT}'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:7.0.5-alpine
    environment:
      - REDIS_PASSWORD= ${REDIS_PASSWORD}
    volumes:
      - redis:/data/redis
    ports:
      - '6379:${REDIS_PORT}'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis: